### ISSUE TITLE
Resolve csrf support issue

### ISSUE THREAD

**Issue by alexeuler** [shakacode/reactrails-react-native-client#2]

**Comment by dansjensen** [comment]
What is the issue? Don't we use jwt tokens?

**Comment by justin808** [comment]
This is done in the tutorial here for the web.

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/libs/metaTagsManager.js#L10

This is why we do this in web apps, per the [Rails Guide](http://guides.rubyonrails.org/security.html#csrf-countermeasures).

The issue is probably that since we don't have any login for the client app, then there's nothing secure. Maybe we can make some API call that does not require the CRSF and send back some magic token, and that is valid for API calls, we turn off CSRF validation.

We'll have to research this a bit.

**Comment by alexeuler** [comment]
Basically, since everybody can do an arbitrary post request for this app, I think it makes no sense to do CSRF or some other sort of protection here.
